//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace BusinessObjects {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.peaksware.com/PWX/1/0", IsNullable=false)]
    public partial class pwx {
        
        private pwxWorkout[] workoutField;
        
        private pwxExtension extensionField;
        
        private string versionField;
        
        private string creatorField;
        
        public pwx() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workout")]
        public pwxWorkout[] workout {
            get {
                return this.workoutField;
            }
            set {
                this.workoutField = value;
            }
        }
        
        /// <remarks/>
        public pwxExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkout {
        
        private athlete athleteField;
        
        private string goalField;
        
        private sportTypes sportTypeField;
        
        private bool sportTypeFieldSpecified;
        
        private string titleField;
        
        private string cmtField;
        
        private string codeField;
        
        private device deviceField;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private summaryData summarydataField;
        
        private pwxWorkoutSegment[] segmentField;
        
        private pwxWorkoutSample[] sampleField;
        
        private pwxWorkoutExtension extensionField;
        
        private string idField;
        
        /// <remarks/>
        public athlete athlete {
            get {
                return this.athleteField;
            }
            set {
                this.athleteField = value;
            }
        }
        
        /// <remarks/>
        public string goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        public sportTypes sportType {
            get {
                return this.sportTypeField;
            }
            set {
                this.sportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sportTypeSpecified {
            get {
                return this.sportTypeFieldSpecified;
            }
            set {
                this.sportTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public device device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public summaryData summarydata {
            get {
                return this.summarydataField;
            }
            set {
                this.summarydataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("segment")]
        public pwxWorkoutSegment[] segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public pwxWorkoutSample[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        public pwxWorkoutExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class athlete {
        
        private string nameField;
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class minMaxAvg {
        
        private double maxField;
        
        private bool maxFieldSpecified;
        
        private double minField;
        
        private bool minFieldSpecified;
        
        private double avgField;
        
        private bool avgFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpecified {
            get {
                return this.maxFieldSpecified;
            }
            set {
                this.maxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minSpecified {
            get {
                return this.minFieldSpecified;
            }
            set {
                this.minFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double avg {
            get {
                return this.avgField;
            }
            set {
                this.avgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avgSpecified {
            get {
                return this.avgFieldSpecified;
            }
            set {
                this.avgFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class summaryData {
        
        private double beginningField;
        
        private double durationField;
        
        private double durationstoppedField;
        
        private bool durationstoppedFieldSpecified;
        
        private double workField;
        
        private bool workFieldSpecified;
        
        private double tssField;
        
        private bool tssFieldSpecified;
        
        private double normalizedPowerField;
        
        private bool normalizedPowerFieldSpecified;
        
        private minMaxAvg hrField;
        
        private minMaxAvg spdField;
        
        private minMaxAvg pwrField;
        
        private minMaxAvg torqField;
        
        private minMaxAvg cadField;
        
        private double distField;
        
        private bool distFieldSpecified;
        
        private minMaxAvg altField;
        
        private minMaxAvg tempField;
        
        private int variabilityIndexField;
        
        private bool variabilityIndexFieldSpecified;
        
        private double climbingelevationField;
        
        private bool climbingelevationFieldSpecified;
        
        private double descendingelevationField;
        
        private bool descendingelevationFieldSpecified;
        
        private summaryDataExtension extensionField;
        
        /// <remarks/>
        public double beginning {
            get {
                return this.beginningField;
            }
            set {
                this.beginningField = value;
            }
        }
        
        /// <remarks/>
        public double duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public double durationstopped {
            get {
                return this.durationstoppedField;
            }
            set {
                this.durationstoppedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationstoppedSpecified {
            get {
                return this.durationstoppedFieldSpecified;
            }
            set {
                this.durationstoppedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double work {
            get {
                return this.workField;
            }
            set {
                this.workField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool workSpecified {
            get {
                return this.workFieldSpecified;
            }
            set {
                this.workFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double tss {
            get {
                return this.tssField;
            }
            set {
                this.tssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tssSpecified {
            get {
                return this.tssFieldSpecified;
            }
            set {
                this.tssFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double normalizedPower {
            get {
                return this.normalizedPowerField;
            }
            set {
                this.normalizedPowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool normalizedPowerSpecified {
            get {
                return this.normalizedPowerFieldSpecified;
            }
            set {
                this.normalizedPowerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg hr {
            get {
                return this.hrField;
            }
            set {
                this.hrField = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg spd {
            get {
                return this.spdField;
            }
            set {
                this.spdField = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg pwr {
            get {
                return this.pwrField;
            }
            set {
                this.pwrField = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg torq {
            get {
                return this.torqField;
            }
            set {
                this.torqField = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg cad {
            get {
                return this.cadField;
            }
            set {
                this.cadField = value;
            }
        }
        
        /// <remarks/>
        public double dist {
            get {
                return this.distField;
            }
            set {
                this.distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distSpecified {
            get {
                return this.distFieldSpecified;
            }
            set {
                this.distFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg alt {
            get {
                return this.altField;
            }
            set {
                this.altField = value;
            }
        }
        
        /// <remarks/>
        public minMaxAvg temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
            }
        }
        
        /// <remarks/>
        public int variabilityIndex {
            get {
                return this.variabilityIndexField;
            }
            set {
                this.variabilityIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variabilityIndexSpecified {
            get {
                return this.variabilityIndexFieldSpecified;
            }
            set {
                this.variabilityIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double climbingelevation {
            get {
                return this.climbingelevationField;
            }
            set {
                this.climbingelevationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool climbingelevationSpecified {
            get {
                return this.climbingelevationFieldSpecified;
            }
            set {
                this.climbingelevationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double descendingelevation {
            get {
                return this.descendingelevationField;
            }
            set {
                this.descendingelevationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descendingelevationSpecified {
            get {
                return this.descendingelevationFieldSpecified;
            }
            set {
                this.descendingelevationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public summaryDataExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class summaryDataExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class device {
        
        private string makeField;
        
        private string modelField;
        
        private double stopdetectionsettingField;
        
        private bool stopdetectionsettingFieldSpecified;
        
        private double elevationchangesettingField;
        
        private bool elevationchangesettingFieldSpecified;
        
        private deviceExtension extensionField;
        
        private string idField;
        
        /// <remarks/>
        public string make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public double stopdetectionsetting {
            get {
                return this.stopdetectionsettingField;
            }
            set {
                this.stopdetectionsettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopdetectionsettingSpecified {
            get {
                return this.stopdetectionsettingFieldSpecified;
            }
            set {
                this.stopdetectionsettingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double elevationchangesetting {
            get {
                return this.elevationchangesettingField;
            }
            set {
                this.elevationchangesettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool elevationchangesettingSpecified {
            get {
                return this.elevationchangesettingFieldSpecified;
            }
            set {
                this.elevationchangesettingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public deviceExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class deviceExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peaksware.com/PWX/1/0")]
    public enum sportTypes {
        
        /// <remarks/>
        Bike,
        
        /// <remarks/>
        Run,
        
        /// <remarks/>
        Walk,
        
        /// <remarks/>
        Swim,
        
        /// <remarks/>
        Brick,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Cross train")]
        Crosstrain,
        
        /// <remarks/>
        Race,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Day Off")]
        DayOff,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mountain Bike")]
        MountainBike,
        
        /// <remarks/>
        Strength,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("XC Ski")]
        XCSki,
        
        /// <remarks/>
        Rowing,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkoutSegment {
        
        private string nameField;
        
        private summaryData summarydataField;
        
        private pwxWorkoutSegmentExtension extensionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public summaryData summarydata {
            get {
                return this.summarydataField;
            }
            set {
                this.summarydataField = value;
            }
        }
        
        /// <remarks/>
        public pwxWorkoutSegmentExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkoutSegmentExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkoutSample {
        
        private double timeoffsetField;
        
        private byte hrField;
        
        private bool hrFieldSpecified;
        
        private double spdField;
        
        private bool spdFieldSpecified;
        
        private short pwrField;
        
        private bool pwrFieldSpecified;
        
        private double torqField;
        
        private bool torqFieldSpecified;
        
        private byte cadField;
        
        private bool cadFieldSpecified;
        
        private double distField;
        
        private bool distFieldSpecified;
        
        private double latField;
        
        private bool latFieldSpecified;
        
        private double lonField;
        
        private bool lonFieldSpecified;
        
        private double altField;
        
        private bool altFieldSpecified;
        
        private double tempField;
        
        private bool tempFieldSpecified;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private pwxWorkoutSampleExtension extensionField;
        
        /// <remarks/>
        public double timeoffset {
            get {
                return this.timeoffsetField;
            }
            set {
                this.timeoffsetField = value;
            }
        }
        
        /// <remarks/>
        public byte hr {
            get {
                return this.hrField;
            }
            set {
                this.hrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hrSpecified {
            get {
                return this.hrFieldSpecified;
            }
            set {
                this.hrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double spd {
            get {
                return this.spdField;
            }
            set {
                this.spdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spdSpecified {
            get {
                return this.spdFieldSpecified;
            }
            set {
                this.spdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short pwr {
            get {
                return this.pwrField;
            }
            set {
                this.pwrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pwrSpecified {
            get {
                return this.pwrFieldSpecified;
            }
            set {
                this.pwrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double torq {
            get {
                return this.torqField;
            }
            set {
                this.torqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool torqSpecified {
            get {
                return this.torqFieldSpecified;
            }
            set {
                this.torqFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte cad {
            get {
                return this.cadField;
            }
            set {
                this.cadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadSpecified {
            get {
                return this.cadFieldSpecified;
            }
            set {
                this.cadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dist {
            get {
                return this.distField;
            }
            set {
                this.distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distSpecified {
            get {
                return this.distFieldSpecified;
            }
            set {
                this.distFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latSpecified {
            get {
                return this.latFieldSpecified;
            }
            set {
                this.latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lonSpecified {
            get {
                return this.lonFieldSpecified;
            }
            set {
                this.lonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double alt {
            get {
                return this.altField;
            }
            set {
                this.altField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altSpecified {
            get {
                return this.altFieldSpecified;
            }
            set {
                this.altFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tempSpecified {
            get {
                return this.tempFieldSpecified;
            }
            set {
                this.tempFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public pwxWorkoutSampleExtension extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkoutSampleExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxWorkoutExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.peaksware.com/PWX/1/0")]
    public partial class pwxExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}
